name: data_pipeline_api
channels:
  - defaults
dependencies:
  # install dependencies
  - python=3.7
  - networkx=2.4
  - matplotlib=3.1.3
  - pandas=1.0.3
  - toml=0.9.4
  - h5py=2.10.0
  - scipy=1.4.1
  - pyyaml=5.3.1
  - semver=2.9.0
  - fsspec=0.7.4
  - s3fs=0.4.2
  - click=7.1.2
  - requests=2.23.0
  - paramiko=2.7.1

  # test dependencies
  - coverage=5.0
  - pytest=5.4.1
  - pytest-cov=2.8.1
