data_directory: .
access_log: access-{run_id}.yaml
fail_on_hash_mismatch: True

read:
  - where:
      data_product: human/mixing-matrix
      component: mixing-matrix
  - where:
      data_product: human/commutes
  - where:
      data_product: human/compartment-transition
  - where:
      data_product: human/population
      version: 0.1.0


write:
  - where:
      {}
    use:
      source: simple_network_sim
